### PR TITLE
Add FCM messaging.

### PR DESCRIPTION
**Pull request by mhmyesman**
This adds methods needed to send Firebase messages, and removes deprecated code.

### CODE REVIEW

**Review by zacharymnp — COMMENTED** [review]
Why did you not remove the deprecated method fromBase64? No form of the method needs to be in the Dawnn server, as far as I can tell.

**Comment by mhmyesman** [comment]
Good point, I don't think we need the ImageUtils class at all, since we won't be digging up any metadata, nor converting to and fro base64.

I'll remove it now.

**Review by zacharymnp — COMMENTED** [review]
In toBase64 (and perhaps something similar in fromBase64), a conversion failure will result in the String "[null]" being returned, rather than "null" or a null value.

Edit- Just saw you delete the class, so I guess it's irrelevant

**Comment by mhmyesman** [comment]
Yup, we're moving to letting the client [handle this](https://github.com/dawnn-team/dawnn_client/blob/main/lib/src/navigation/image_page.dart#L122).

**Review by zacharymnp — APPROVED** [review]
This looks workable.

**Pull request merged**
